install.packages("blogdown")
blogdown::install_hugo()
blogdown::update_hugo()
install.packages("ggthemes")
install.packages("plotly")
install.packages("esquisse")
remotes::install_github("rstudio/gt")
